create or replace database DEV_DB;

create or replace schema DEV_SCHEMA;

create or replace TABLE AE_TEST (
	C1 VARCHAR(16777216)
);
create or replace TABLE DATE_LTZ (
	DATE TIMESTAMP_LTZ(9)
);
create or replace TABLE DATE_TEST (
	DATE TIMESTAMP_NTZ(9)
);
create or replace TABLE EMP (
	EMPNO NUMBER(38,0),
	ENAME VARCHAR(16777216),
	JOB VARCHAR(30),
	SAL FLOAT,
	DEPTNO NUMBER(38,0)
);
create or replace TABLE EMPLOYEE (
	ID NUMBER(38,0),
	NAME VARCHAR(16777216),
	ADDRESS VARCHAR(16777216),
	START_DATE DATE
);
create or replace TABLE REAL_DATATYPE (
	REALDATA FLOAT
);
create or replace TABLE SAMPLE_TABLE (
	ID NUMBER(38,0)
);
create or replace TABLE TEST6 (
	ID NUMBER(38,0)
);
create or replace TABLE TEST_2 (
	FILEDATE VARCHAR(16777216),
	FILENUMBER NUMBER(38,0),
	ROWNUMBER NUMBER(38,0),
	SOMECOL1 NUMBER(38,0),
	SOMECOL2 VARCHAR(16777216),
	SOMECOL3 VARCHAR(16777216)
);
create or replace TABLE TEST_5 (
	FILENUMBER NUMBER(38,0),
	ROWNUMBER NUMBER(38,0),
	SOMECOL1 NUMBER(38,0),
	SOMECOL2 VARCHAR(16777216),
	SOMECOL3 VARCHAR(16777216)
);
create or replace TABLE USER_LIST (
	ID NUMBER(38,0),
	NAME VARCHAR(16777216)
);
create or replace TABLE VARIANT_DEMO (
	DATA VARIANT
)COMMENT='Table to demonstrate the variant data type'
;
create or replace TABLE "oracle_date" (
	ID_NUM VARCHAR(32700),
	START_DT VARCHAR(32700),
	END_DT_TS VARCHAR(32700)
);
create or replace TABLE "test1" (
	ID NUMBER(38,0),
	ID_$ NUMBER(38,0)
);
create or replace TABLE "test1_spl" (
	ID NUMBER(38,0),
	"id_$" NUMBER(38,0)
);
create or replace TABLE "test3" (
	"id" NUMBER(38,0),
	"id_$" NUMBER(38,0)
);
create or replace TABLE "test3-child" (
	"id" NUMBER(38,0),
	"id_$" NUMBER(38,0)
);
create or replace TABLE "test4" (
	ID NUMBER(38,0),
	ID_1 NUMBER(38,0),
	"id_2" NUMBER(38,0)
);
create or replace TABLE "test_emp_krishna" (
	EMPNO NUMBER(38,0),
	ENAME VARCHAR(25),
	JOB VARCHAR(10),
	TEST_SPL_COLUMN_$ VARCHAR(5)
);
create or replace schema POS;

create or replace TABLE REVENUE_SUMMARY_MASHGIN_STG (
	LOCATION_ID VARCHAR(50),
	OBJECT_NAME VARCHAR(40),
	START_TIME DATE,
	END_TIME DATE,
	SALES_TOTAL NUMBER(22,5),
	SUB_TOTAL NUMBER(22,5),
	TRANSACTIONS NUMBER(38,0),
	AVERAGE_TICKET NUMBER(22,5),
	SOURCE_SYSTEM_ID NUMBER(38,0),
	CREATE_DATE DATE
);
create or replace TABLE REVENUE_SUMMARY_TAPINGO_STG (
	NUMBER_OF_CONSUMERS NUMBER(38,0),
	AVG_CHECK NUMBER(22,5),
	TOTAL_AMOUNT NUMBER(22,5),
	TRANS_DATE_SORT VARCHAR(10),
	TAX NUMBER(22,5),
	NUMBER_OF_ORDERS NUMBER(38,0),
	TIP NUMBER(22,5),
	DAY_OF_WEEK VARCHAR(10),
	SHOP_NAME VARCHAR(250),
	TOTAL_MEAL_VALUE NUMBER(22,5),
	MERCHANT_TAX NUMBER(22,5),
	TRANSACTION_DATE DATE,
	TAPINGO_FEE NUMBER(22,5),
	SERVICE_FEE NUMBER(22,5),
	SHOP_ID NUMBER(38,0),
	CURRENT_EQUIVALENCE NUMBER(22,5),
	NUMBER_OF_ITEMS NUMBER(38,0),
	AMOUNT_TO_MERCHANT NUMBER(22,5),
	CREATE_DATE DATE,
	SOURCE_SYSTEM_ID NUMBER(38,0)
);
create or replace TABLE REVENUE_SUMMARY_TASK_STG (
	SALE_COUNT NUMBER(38,0),
	AVERAGE_SALE NUMBER(22,5),
	SALES_TOTAL NUMBER(22,5),
	GROSS_TOTAL NUMBER(22,5),
	DISCOUNT_TOTAL NUMBER(22,5),
	TAX_TOTAL NUMBER(22,5),
	ITEMS_SOLD NUMBER(38,0),
	AVERAGE_TRANSACTION_TIME NUMBER(25,15),
	AVERAGE_COVERS NUMBER(25,15),
	LOCATION_NO NUMBER(38,0),
	LOCATION VARCHAR(250),
	SUMMARY_DATE DATE,
	CREATE_DATE DATE,
	SOURCE_SYSTEM_ID NUMBER(38,0)
);
create or replace schema PUBLIC;

create or replace TABLE EMP (
	EMPNO NUMBER(38,0),
	ENAME VARCHAR(16777216),
	JOB VARCHAR(30),
	SAL FLOAT,
	DEPTNO NUMBER(38,0)
);
create or replace TABLE EMP2 (
	EMPNO NUMBER(38,0),
	ENAME VARCHAR(16777216),
	JOB VARCHAR(30),
	SAL FLOAT,
	DEPTNO NUMBER(38,0)
);
create or replace TABLE "Withdollarsign" (
	ID NUMBER(38,0),
	"id" NUMBER(38,0),
	"Id" NUMBER(38,0),
	ID_1_$ NUMBER(38,0),
	"$_Id_1" NUMBER(38,0),
	ID_$_1 NUMBER(38,0)
);
create or replace TABLE "robots" (
	ENAME VARCHAR(25)
);
create or replace TABLE "terence_tablefromoracle" (
	"Testone" VARCHAR(20)
);