create or replace database HPF_POC;

create or replace schema HPC_POC;

create or replace TABLE SERVICINGSCD1TARGET (
	KEY NUMBER(38,0) NOT NULL DEFAULT HPF_POC.HPC_POC.SERVICING_SCD1_TARGET_KEY.NEXTVAL,
	ID NUMBER(38,0) NOT NULL,
	TIME_STAMP DATE NOT NULL,
	LOAN_NUMBER VARCHAR(20) NOT NULL,
	OLD_LOAN_NUMBER VARCHAR(20),
	ZONE VARCHAR(4),
	BRANCH_OFFICER_CODE VARCHAR(255),
	EMPLOYEE_CODE VARCHAR(4),
	LOAN_PURPOSE NUMBER(38,0),
	ORIGINAL_OCCUPANCY_STATUS NUMBER(38,0),
	HI_TYPE NUMBER(38,0),
	LO_TYPE NUMBER(38,0),
	PROPERTY_CITY_NAME VARCHAR(80),
	PROPERTY_STATE VARCHAR(2),
	PROPERTY_ZIP VARCHAR(9),
	ZIP_CODE_SUFFIX VARCHAR(4),
	PROPERTY_TYPE VARCHAR(1),
	SMSA_TRACK_CODE VARCHAR(12),
	SMSA_CODE VARCHAR(12),
	PROPERTY_STATE_CODE NUMBER(38,0),
	LAST_UPDATE_DATE TIMESTAMP_NTZ(9) NOT NULL
);
create or replace TABLE SERVICINGSCD2TARGET (
	KEY_ID NUMBER(38,0) NOT NULL DEFAULT HPF_POC.HPC_POC.SERVICING_SCD2_TARGET_KEY.NEXTVAL,
	TIME_STAMP DATE NOT NULL,
	LOAN_NUMBER VARCHAR(20) NOT NULL,
	OLD_LOAN_NUMBER VARCHAR(20),
	ZONE VARCHAR(4),
	BRANCH_OFFICER_CODE VARCHAR(255),
	EMPLOYEE_CODE VARCHAR(4),
	LOAN_PURPOSE NUMBER(38,0),
	ORIGINAL_OCCUPANCY_STATUS NUMBER(38,0),
	HI_TYPE NUMBER(38,0),
	LO_TYPE NUMBER(38,0),
	PROPERTY_CITY_NAME VARCHAR(80),
	PROPERTY_STATE VARCHAR(2),
	PROPERTY_ZIP VARCHAR(9),
	ZIP_CODE_SUFFIX VARCHAR(4),
	PROPERTY_TYPE VARCHAR(1),
	SMSA_TRACK_CODE VARCHAR(12),
	SMSA_CODE VARCHAR(12),
	PROPERTY_STATE_CODE NUMBER(38,0),
	RECORD_BEGIN_DATE DATE NOT NULL,
	RECORD_END_DATE DATE,
	CURRENT_RECORD_FLAG NUMBER(38,0) NOT NULL,
	RECORD_DELETE_FLAG NUMBER(38,0) NOT NULL,
	LAST_UPDATE_DATE TIMESTAMP_NTZ(9) NOT NULL
);
create or replace sequence SCD1SEQ start with 1 increment by 1;
create or replace sequence SCD2SEQ start with 1 increment by 1;
create or replace sequence SERVICING_SCD1_TARGET_KEY start with 1 increment by 1;
create or replace sequence SERVICING_SCD2_TARGET_KEY start with 1 increment by 1;
create or replace schema PUBLIC;

create or replace TABLE SERVICINGSCD1TARGET (
	KEY_ID NUMBER(38,0) NOT NULL DEFAULT HPF_POC.PUBLIC.SERVICING_SCD1_TARGET_KEY.NEXTVAL,
	ID NUMBER(38,0) NOT NULL,
	TIME_STAMP DATE NOT NULL,
	LOAN_NUMBER VARCHAR(20) NOT NULL,
	OLD_LOAN_NUMBER VARCHAR(20),
	ZONE VARCHAR(4),
	BRANCH_OFFICER_CODE VARCHAR(255),
	EMPLOYEE_CODE VARCHAR(4),
	LOAN_PURPOSE NUMBER(38,0),
	ORIGINAL_OCCUPANCY_STATUS NUMBER(38,0),
	HI_TYPE NUMBER(38,0),
	LO_TYPE NUMBER(38,0),
	PROPERTY_CITY_NAME VARCHAR(80),
	PROPERTY_STATE VARCHAR(2),
	PROPERTY_ZIP VARCHAR(9),
	ZIP_CODE_SUFFIX VARCHAR(4),
	PROPERTY_TYPE VARCHAR(1),
	SMSA_TRACK_CODE VARCHAR(12),
	SMSA_CODE VARCHAR(12),
	PROPERTY_STATE_CODE NUMBER(38,0),
	LAST_UPDATE_DATE TIMESTAMP_NTZ(9) NOT NULL
);
create or replace TABLE SERVICINGSCD2TARGET (
	KEY_ID NUMBER(38,0) NOT NULL DEFAULT HPF_POC.PUBLIC.SERVICING_SCD2_TARGET_KEY.NEXTVAL,
	TIME_STAMP DATE NOT NULL,
	LOAN_NUMBER VARCHAR(20) NOT NULL,
	OLD_LOAN_NUMBER VARCHAR(20),
	ZONE VARCHAR(4),
	BRANCH_OFFICER_CODE VARCHAR(255),
	EMPLOYEE_CODE VARCHAR(4),
	LOAN_PURPOSE NUMBER(38,0),
	ORIGINAL_OCCUPANCY_STATUS NUMBER(38,0),
	HI_TYPE NUMBER(38,0),
	LO_TYPE NUMBER(38,0),
	PROPERTY_CITY_NAME VARCHAR(80),
	PROPERTY_STATE VARCHAR(2),
	PROPERTY_ZIP VARCHAR(9),
	ZIP_CODE_SUFFIX VARCHAR(4),
	PROPERTY_TYPE VARCHAR(1),
	SMSA_TRACK_CODE VARCHAR(12),
	SMSA_CODE VARCHAR(12),
	PROPERTY_STATE_CODE NUMBER(38,0),
	RECORD_BEGIN_DATE DATE NOT NULL,
	RECORD_END_DATE DATE,
	CURRENT_RECORD_FLAG NUMBER(38,0) NOT NULL,
	RECORD_DELETE_FLAG NUMBER(38,0) NOT NULL,
	LAST_UPDATE_DATE TIMESTAMP_NTZ(9) NOT NULL
);
create or replace sequence SERVICING_SCD1_TARGET_KEY start with 1 increment by 1;
create or replace sequence SERVICING_SCD2_TARGET_KEY start with 1 increment by 1;